language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - "wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh"
  - "chmod +x miniconda.sh"
  - "./miniconda.sh -b"
  - "export PATH=/home/travis/miniconda2/bin:$PATH"
  - "conda update --yes conda"
  - "conda info -a"

install:
  - "conda create --yes -n test-env python=$TRAVIS_PYTHON_VERSION pip>=9.0 coverage>=4.2"
  - "source activate test-env"
  - "conda config --add channels conda-forge"
  - "conda install --yes numpy>=1.10 cython>=0.25 pyproj>=1.9 gdal>=2.1 libgdal>=2.1 shapely>=1.5"
  - "conda list"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install . --no-deps"
  - "rm -rf karta/"   # clean-up to workaround coverage.py scanning karta/ dir
                      # while karta module is installed by pip elsewhere

script:
  coverage run --source=karta tests/runtests.py && coverage report

after_success:
  coveralls

sudo:   # container-based testing
  false
