environment:

  matrix:

    - PYTHON_VERSION: "2.7"
      MINICONDA: "C:\\Miniconda"

    - PYTHON_VERSION: "3.5"
      MINICONDA: "C:\\Miniconda3"

    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda3"

    - PYTHON_VERSION: "2.7"
      MINICONDA: "C:\\Miniconda-x64"

    - PYTHON_VERSION: "3.5"
      MINICONDA: "C:\\Miniconda3-x64"

    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda3-x64"

install:

  - "ECHO %PYTHON_VERSION% %MINICONDA%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy cython setuptools"
  - "activate test-environment"
  - "conda install -c conda-forge gdal=2.1.3"

  - "pip install -U picogeojson blosc coverage"
  - "cd C:\\projects\\karta"
  - "pip install . --no-deps"

test_script:
  - "build.cmd python tests\\runtests.py"

